import tw from 'twin.macro'
import { FRAME_RATE } from 'configs/constant'

export const me = [
  {
    label: 'exp',
    anim: 'star',
    configs: { loop: 4 * FRAME_RATE + 4, changeRate: FRAME_RATE / 2 },
  },
  {
    anim: 'flick',
    options: { model: 'sand' },
  },
  {
    anim: 'flick',
    configs: { changeRate: 9 * FRAME_RATE },
    options: { model: 'sand_freeze' },
  },
]

export const messages = [
  {
    anim: 'typing',
    configs: { addStartTime: FRAME_RATE / 2, addX: -10, addY: -5, changeRate: 2 * FRAME_RATE, freeze: 10 * FRAME_RATE },
    options: {
      messages: [
        'Experiences (1/4)',
        '',
        '@ Silicon Craft Technology PLC',
        '> Lead Product Engineer [08/2020 – present]',
        ' - Take care all NFC products.',
        '   - IC products owner. (drive the business)',
        '   - Technology trend and market research.',
        '',
        '> Lead Embedded System Engineer [04/2020 – 07/2020]',
        ' - NFC customer projects.',
        ' - New NFC solution with customer',
        ' - Android application consultant',
        '',
      ],
      styles: [
        tw`text-purple-300`,
        ,
        tw`text-green-300`,
        tw`text-blue-300`,
        tw`text-white`,
        tw`text-gray-300 text-sm`,
        tw`text-gray-300 text-sm`,
        ,
        tw`text-blue-300`,
        tw`text-white`,
        tw`text-white`,
        tw`text-white`,
      ],
    },
    labelAt: 'exp',
  },
  {
    anim: 'typing',
    configs: { addStartTime: FRAME_RATE / 2, changeRate: 2 * FRAME_RATE, freeze: 10 * FRAME_RATE },
    options: {
      messages: [
        'Experiences (2/4)',
        '',
        '@Ever Medical Technologies',
        '> Lead Full Stack Developer [11/2018 – 02/2020]',
        ' - Create Healthcare web platform (React/Loopback)',
        '   - OMA Healthcare Platform. (ever.healthcare)',
        '   - Admin Portal for Operators. (ant design)',
        '   - OMA Platform mobile version. (react-native)',
        '',
        '',
        '',
        '',
        ,
      ],
      styles: [
        tw`text-purple-300`,
        ,
        tw`text-green-300`,
        tw`text-blue-300`,
        tw`text-white`,
        tw`text-gray-300 text-sm`,
        tw`text-gray-300 text-sm`,
        tw`text-gray-300 text-sm`,
      ],
    },
  },
  {
    anim: 'typing',
    configs: { addStartTime: FRAME_RATE / 2, changeRate: 2 * FRAME_RATE, freeze: 10 * FRAME_RATE },
    options: {
      messages: [
        'Experiences (3/4)',
        '',
        'Freelance',
        '> Software Developer [05/2018 - 10/2018]',
        ' - POS (Point-of-Sale) system.',
        ' - Android application of NFC technology.',
        ' - Configurator software for testing machine.',
        ' - Image matching detection library.',
        ' - SPA Frontend for managing the FPGA info.',
        '',
        '',
        '',
        '',
      ],
      styles: [
        tw`text-purple-300`,
        ,
        tw`text-green-300`,
        tw`text-blue-300`,
        tw`text-white`,
        tw`text-white`,
        tw`text-white`,
        tw`text-white`,
        tw`text-white`,
      ],
    },
  },
  {
    anim: 'typing',
    configs: { addStartTime: FRAME_RATE / 2, changeRate: 2 * FRAME_RATE, freeze: 10 * FRAME_RATE },
    options: {
      messages: [
        'Experiences (4/4)',
        '',
        '@Silicon Craft Technology PLC',
        '> Senior Embedded System Engineer [07/2017 – 04/2018]',
        ' - NFC info android application.',
        ' - Embedded board. (STM8/32, MSP430, MCU 4 bit)',
        ' - AES for designing the encrypted product.',
        '',
        '> Embedded System Engineer [04/2013 – 06/2017]',
        ' - Demostration products of NFC technology.',
        ' - Tester boards for company’s ICs.',
        ' - NFC application and library for android.',
        '',
      ],
      styles: [
        tw`text-purple-300`,
        ,
        tw`text-green-300`,
        tw`text-blue-300`,
        tw`text-white`,
        tw`text-white`,
        tw`text-white`,
        ,
        tw`text-blue-300`,
        tw`text-white`,
        tw`text-white`,
        tw`text-white`,
      ],
    },
  },
]

export default [...me, ...messages]
